### ISSUE TITLE
NullPointerException if missing symbols at EOF

### ISSUE THREAD

**Issue by Peaupote** [nobrakal/picd#1]
For instance 

```
Begin
  FillRect(0,0,10,10,#000000);
End
```
throws the following error

```
java.lang.NullPointerException
	at src.exceptions.UnexpectedSymbolException.<init>(UnexpectedSymbolException.java:15)
	at src.parsers.LookAhead1.eat(LookAhead1.java:67)
	at src.parsers.ASTParser.suiteInstructions(ASTParser.java:48)
	at src.parsers.ASTParser.parse(ASTParser.java:35)
```

Because current is null.

**Comment by nobrakal** [comment]
On en est où ?

**Comment by Peaupote** [comment]
nul part, je vais corriger ça vite fait
